name: tmkacademy
description: "A project to learn about programming in Shan language!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  printing: ^5.14.2
  pdf: ^3.11.3
  markdown: ^7.3.0
  htmltopdfwidgets: ^2.0.1
  flutter_svg: ^2.3.0
  simple_icons:
    git:
      url: https://github.com/jlnrrg/simple_icons
      ref: develop


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/lessons/
    - assets/lessons/java/
    - assets/lessons/python/
    - assets/lessons/basic/
    - assets/lessons/dart/
    - assets/lessons/html/
    - assets/lessons/css/
    - assets/lessons/js/
    - assets/lessons/kotlin/
    - assets/lessons/c/
    - assets/lessons/haskell/
    - assets/lessons/ts/
    - assets/lessons/csharp/
    - assets/lessons/python_tkinter/
    - assets/lessons/git/
    - assets/lessons/javafx/
    - assets/lessons/cpp/
    - assets/lessons/mysql/
    - assets/lessons/java_springboot/
    - assets/lessons/jetpack_compose/
    - assets/lessons/android_keyboard/
    - assets/lessons/android_xml_kotlin/
    - assets/lessons/swift/
    - assets/lessons/swift_ui/
    - assets/lessons/ios_keyboard/
    - assets/images/
    - assets/icons/
  fonts:
    - family: AJ05
      fonts:
        - asset: assets/fonts/aj05.ttf

    - family: AJ03
      fonts:
        - asset: assets/fonts/aj03.ttf

    - family: AJ13
      fonts:
        - asset: assets/fonts/aj13.ttf

    - family: AJ06
      fonts:
        - asset: assets/fonts/aj06.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#D4A373" # Matches your blue theme
  adaptive_icon_foreground: "assets/images/app_icon.png"

  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    backgroundColor: "#3E2723" # Your kJavaMocha
    themeColor: "#3E2723"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # Windows standard icon size
