const languages = [
  "basic",
  "python",
  "java",
  "kotlin",
  "dart",
  "html",
  "css",
  "js",
  "ts",
  "c",
  "cpp",
  "csharp",
  "swift",
  "swift_ui",
  "ios_keyboard",
  "haskell",
  "javafx",
  "java_springboot",
  "python_tkinter",
  "android_xml_kotlin",
  "jetpack_compose",
  "git",
  "mysql",
  "android_keyboard"
];
const fullName = {
  "basic": "Computer Basic",
  "python": "Python",
  "java": "Java",
  "kotlin": "Kotlin",
  "dart": "Dart",
  "html": "HTML",
  "css": "CSS",
  "swift": "Swift",
  "swift_ui": "Swift UI",
  "ios_keyboard": "iOS Keyboard",
  "js": "Javascript",
  "android_xml_kotlin": "Android XML with Kotlin",
  "jetpack_compose": "Android Jetpack Compose",
  "ts": "Typescript",
  "c": "C",
  "cpp": "C++",
  "csharp": "C#",
  "haskell": "Haskell",
  "python_tkinter": "Python Tkinter",
  "javafx": "JavaFX",
  "git": "Git & Github",
  "mysql": "MySQL",
  "java_springboot": "Java Spring Boot",
  "android_keyboard": "Android Keyboard"
};
